CREATE TABLE Customers (
    ID INTEGER NOT NULL,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Username NVARCHAR(50) NOT NULL,
    Role NVARCHAR(50) NOT NULL,
    Team NVARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)
);